package dev.jorm.client;

import java.util.List;
import java.util.Optional;

/**
 * Base interface for all clients generated by Jorm.
 * T: The entity type (Record)
 * ID: The primary key type
 */
public interface ModelClient<T, ID> {
    
    List<T> findMany();
    
    Optional<T> findById(ID id);
    
    T create(T data);
    
    T update(ID id, T data);
    
    void delete(ID id);
}
